### ISSUE TITLE
Joint Bert模型复现结果和Slot Filling F1值计算方式

### ISSUE THREAD

**Issue by JiDong-CS** [sz128/slot_filling_and_intent_detection_of_SLU#3]
您好，我想问一下Results部分是复现的结果吗？我发现表格中的结果与原论文中的结果好像是一样的，所以有些疑惑。具体地，我比较关注Joint Bert模型，请问您的实现中，槽位F1值的计算方式是什么样的（我不太熟悉Pytorch，您的代码我刚刚看，希望能得到您的解答）？

**Comment by sz128** [comment]
Results部分 关于 Joint Bert模型 的结果我是直接取的原论文中的结果。Slot-F1 score 计算方式是和经典 conlleval.pl 脚本一致的。比如：

annotation:  O, O, B-C, I-C,  O, B-D, B-E
prediction:   O, O, O,     B-C, O, B-D, O

Precision = 1/2
Recall = 1/3

**Comment by JiDong-CS** [comment]
那请问您复现的结果和原文接近吗？

**Comment by sz128** [comment]
是接近的。

**Comment by JiDong-CS** [comment]
> 是接近的。

好的，感谢！

**Comment by sz128** [comment]
> > 是接近的。
> 
> 好的，感谢！

不客气！
