### ISSUE TITLE
是否仅支持BIO标注方式，支持BIEO、BIESO吗

### ISSUE THREAD

**Issue by bigrat911** [sz128/slot_filling_and_intent_detection_of_SLU#4]

**Comment by sz128** [comment]
这类标注方式是和模型无关的。标注方式不同，受影响的两个地方分别是：
1. 数据标注文件的label；
2. 评测脚本(utils/acc.py)的"get_chunks"。目前我们支持BIO、BIEO，您如果有需求，可以自行修改该函数。

**Comment by sz128** [comment]
目前 utils/acc.py 已经支持 IOBES 格式。
