### ISSUE TITLE
Error ve3_cu90_pt_1.0/bin/activate: No such file or directory

### ISSUE THREAD

**Issue by xiaominghero** [sz128/slot_filling_and_intent_detection_of_SLU#5]
I run the command
bash run/atis_with_pretrained_word_embeddings.sh slot_tagger

the error like this.
./path.sh: line 2: /home/xx/ve3_cu90_pt_1.0/bin/activate: No such file or directory

ve3_cu90_pt_1.0 is ? how i can fix this ?

thank you

**Comment by sz128** [comment]
The path "~/ve3_cu90_pt_1.0/bin/activate" is a [virtual environment](https://virtualenv.pypa.io/en/latest/) used in my computer. Now, I have updated "./path.sh" to be silent when the path doesn't exist. Meanwhile, you can also setup a virtual environment in your computer.
