### ISSUE TITLE
Inference Mode

### ISSUE THREAD

**Issue by maggieezzat** [sz128/slot_filling_and_intent_detection_of_SLU#7]
Hello. After training the model, how can I deploy it and use it in inference mode??

**Comment by sz128** [comment]
Hi @maggieezzat . Sorry for the delay.

You can find an example now:
```
bash run/atis_with_pretrained_word_embeddings_for_inference_mode__an_example.sh
```

It contains two parts:
1. Loading vocabularies and models from an experiment path after training.
2. Using the vocabularies and models for decoding and evaluation.
